from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from .substrait.ibis import algebra_pb2 as substrait_dot_ibis_dot_algebra__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='extension_rels.proto', package='arrow.substrait_ext', syntax='proto3', serialized_options=b'\n\x12io.arrow.substraitP\x01Z!github.com/apache/arrow/substrait\xaa\x02\x0fArrow.Substrait', create_key=_descriptor._internal_create_key, serialized_pb=b'\n\x14extension_rels.proto\x12\x13arrow.substrait_ext\x1a\x1csubstrait/ibis/algebra.proto"\xd4\x01\n\x0bAsOfJoinRel\x12@\n\x04keys\x18\x01 \x03(\x0b2,.arrow.substrait_ext.AsOfJoinRel.AsOfJoinKeyR\x04keys\x12\x1c\n\ttolerance\x18\x02 \x01(\x03R\ttolerance\x1ae\n\x0bAsOfJoinKey\x12*\n\x02on\x18\x01 \x01(\x0b2\x1a.substrait.ibis.ExpressionR\x02on\x12*\n\x02by\x18\x02 \x03(\x0b2\x1a.substrait.ibis.ExpressionR\x02by"O\n\x0bNamedTapRel\x12\x12\n\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n\x07columns\x18\x03 \x03(\tR\x07columns"\xf7\x01\n\x15SegmentedAggregateRel\x12N\n\rgrouping_keys\x18\x01 \x03(\x0b2).substrait.ibis.Expression.FieldReferenceR\x0cgroupingKeys\x12L\n\x0csegment_keys\x18\x02 \x03(\x0b2).substrait.ibis.Expression.FieldReferenceR\x0bsegmentKeys\x12@\n\x08measures\x18\x03 \x03(\x0b2$.substrait.ibis.AggregateRel.MeasureR\x08measuresBK\n\x12io.arrow.substraitP\x01Z!github.com/apache/arrow/substrait\xaa\x02\x0fArrow.Substraitb\x06proto3', dependencies=[substrait_dot_ibis_dot_algebra__pb2.DESCRIPTOR])
_ASOFJOINREL_ASOFJOINKEY = _descriptor.Descriptor(name='AsOfJoinKey', full_name='arrow.substrait_ext.AsOfJoinRel.AsOfJoinKey', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='on', full_name='arrow.substrait_ext.AsOfJoinRel.AsOfJoinKey.on', index=0, number=1, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='on', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='by', full_name='arrow.substrait_ext.AsOfJoinRel.AsOfJoinKey.by', index=1, number=2, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='by', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=187, serialized_end=288)
_ASOFJOINREL = _descriptor.Descriptor(name='AsOfJoinRel', full_name='arrow.substrait_ext.AsOfJoinRel', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='keys', full_name='arrow.substrait_ext.AsOfJoinRel.keys', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='keys', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='tolerance', full_name='arrow.substrait_ext.AsOfJoinRel.tolerance', index=1, number=2, type=3, cpp_type=2, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='tolerance', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[_ASOFJOINREL_ASOFJOINKEY], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=76, serialized_end=288)
_NAMEDTAPREL = _descriptor.Descriptor(name='NamedTapRel', full_name='arrow.substrait_ext.NamedTapRel', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='kind', full_name='arrow.substrait_ext.NamedTapRel.kind', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='kind', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='name', full_name='arrow.substrait_ext.NamedTapRel.name', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='name', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='columns', full_name='arrow.substrait_ext.NamedTapRel.columns', index=2, number=3, type=9, cpp_type=9, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='columns', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=290, serialized_end=369)
_SEGMENTEDAGGREGATEREL = _descriptor.Descriptor(name='SegmentedAggregateRel', full_name='arrow.substrait_ext.SegmentedAggregateRel', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='grouping_keys', full_name='arrow.substrait_ext.SegmentedAggregateRel.grouping_keys', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='groupingKeys', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='segment_keys', full_name='arrow.substrait_ext.SegmentedAggregateRel.segment_keys', index=1, number=2, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='segmentKeys', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='measures', full_name='arrow.substrait_ext.SegmentedAggregateRel.measures', index=2, number=3, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='measures', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=372, serialized_end=619)
_ASOFJOINREL_ASOFJOINKEY.fields_by_name['on'].message_type = substrait_dot_ibis_dot_algebra__pb2._EXPRESSION
_ASOFJOINREL_ASOFJOINKEY.fields_by_name['by'].message_type = substrait_dot_ibis_dot_algebra__pb2._EXPRESSION
_ASOFJOINREL_ASOFJOINKEY.containing_type = _ASOFJOINREL
_ASOFJOINREL.fields_by_name['keys'].message_type = _ASOFJOINREL_ASOFJOINKEY
_SEGMENTEDAGGREGATEREL.fields_by_name['grouping_keys'].message_type = substrait_dot_ibis_dot_algebra__pb2._EXPRESSION_FIELDREFERENCE
_SEGMENTEDAGGREGATEREL.fields_by_name['segment_keys'].message_type = substrait_dot_ibis_dot_algebra__pb2._EXPRESSION_FIELDREFERENCE
_SEGMENTEDAGGREGATEREL.fields_by_name['measures'].message_type = substrait_dot_ibis_dot_algebra__pb2._AGGREGATEREL_MEASURE
DESCRIPTOR.message_types_by_name['AsOfJoinRel'] = _ASOFJOINREL
DESCRIPTOR.message_types_by_name['NamedTapRel'] = _NAMEDTAPREL
DESCRIPTOR.message_types_by_name['SegmentedAggregateRel'] = _SEGMENTEDAGGREGATEREL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
AsOfJoinRel = _reflection.GeneratedProtocolMessageType('AsOfJoinRel', (_message.Message,), {'AsOfJoinKey': _reflection.GeneratedProtocolMessageType('AsOfJoinKey', (_message.Message,), {'DESCRIPTOR': _ASOFJOINREL_ASOFJOINKEY, '__module__': 'extension_rels_pb2'}), 'DESCRIPTOR': _ASOFJOINREL, '__module__': 'extension_rels_pb2'})
_sym_db.RegisterMessage(AsOfJoinRel)
_sym_db.RegisterMessage(AsOfJoinRel.AsOfJoinKey)
NamedTapRel = _reflection.GeneratedProtocolMessageType('NamedTapRel', (_message.Message,), {'DESCRIPTOR': _NAMEDTAPREL, '__module__': 'extension_rels_pb2'})
_sym_db.RegisterMessage(NamedTapRel)
SegmentedAggregateRel = _reflection.GeneratedProtocolMessageType('SegmentedAggregateRel', (_message.Message,), {'DESCRIPTOR': _SEGMENTEDAGGREGATEREL, '__module__': 'extension_rels_pb2'})
_sym_db.RegisterMessage(SegmentedAggregateRel)
DESCRIPTOR._options = None