"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from ... import substrait
import typing
import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ExpressionReference(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EXPRESSION_FIELD_NUMBER: builtins.int
    MEASURE_FIELD_NUMBER: builtins.int
    OUTPUT_NAMES_FIELD_NUMBER: builtins.int

    @property
    def expression(self) -> substrait.ibis.algebra_pb2.Expression:
        ...

    @property
    def measure(self) -> substrait.ibis.algebra_pb2.AggregateFunction:
        ...

    @property
    def output_names(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Field names in depth-first order"""
        pass

    def __init__(self, *, expression: typing.Optional[substrait.ibis.algebra_pb2.Expression]=..., measure: typing.Optional[substrait.ibis.algebra_pb2.AggregateFunction]=..., output_names: typing.Optional[typing.Iterable[typing.Text]]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['expr_type', b'expr_type', 'expression', b'expression', 'measure', b'measure']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['expr_type', b'expr_type', 'expression', b'expression', 'measure', b'measure', 'output_names', b'output_names']) -> None:
        ...

    def WhichOneof(self, oneof_group: typing_extensions.Literal['expr_type', b'expr_type']) -> typing.Optional[typing_extensions.Literal['expression', 'measure']]:
        ...
global___ExpressionReference = ExpressionReference

class ExtendedExpression(google.protobuf.message.Message):
    """Describe a set of operations to complete.
    For compactness sake, identifiers are normalized at the plan level.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VERSION_FIELD_NUMBER: builtins.int
    EXTENSION_URIS_FIELD_NUMBER: builtins.int
    EXTENSIONS_FIELD_NUMBER: builtins.int
    REFERRED_EXPR_FIELD_NUMBER: builtins.int
    BASE_SCHEMA_FIELD_NUMBER: builtins.int
    ADVANCED_EXTENSIONS_FIELD_NUMBER: builtins.int
    EXPECTED_TYPE_URLS_FIELD_NUMBER: builtins.int

    @property
    def version(self) -> substrait.ibis.plan_pb2.Version:
        """Substrait version of the expression. Optional up to 0.17.0, required for later
        versions.
        """
        pass

    @property
    def extension_uris(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[substrait.ibis.extensions.extensions_pb2.SimpleExtensionURI]:
        """a list of yaml specifications this expression may depend on"""
        pass

    @property
    def extensions(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[substrait.ibis.extensions.extensions_pb2.SimpleExtensionDeclaration]:
        """a list of extensions this expression may depend on"""
        pass

    @property
    def referred_expr(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExpressionReference]:
        """one or more expression trees with same order in plan rel"""
        pass

    @property
    def base_schema(self) -> substrait.ibis.type_pb2.NamedStruct:
        ...

    @property
    def advanced_extensions(self) -> substrait.ibis.extensions.extensions_pb2.AdvancedExtension:
        """additional extensions associated with this expression."""
        pass

    @property
    def expected_type_urls(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """A list of com.google.Any entities that this plan may use. Can be used to
        warn if some embedded message types are unknown. Note that this list may
        include message types that are ignorable (optimizations) or that are
        unused. In many cases, a consumer may be able to work with a plan even if
        one or more message types defined here are unknown.
        """
        pass

    def __init__(self, *, version: typing.Optional[substrait.ibis.plan_pb2.Version]=..., extension_uris: typing.Optional[typing.Iterable[substrait.ibis.extensions.extensions_pb2.SimpleExtensionURI]]=..., extensions: typing.Optional[typing.Iterable[substrait.ibis.extensions.extensions_pb2.SimpleExtensionDeclaration]]=..., referred_expr: typing.Optional[typing.Iterable[global___ExpressionReference]]=..., base_schema: typing.Optional[substrait.ibis.type_pb2.NamedStruct]=..., advanced_extensions: typing.Optional[substrait.ibis.extensions.extensions_pb2.AdvancedExtension]=..., expected_type_urls: typing.Optional[typing.Iterable[typing.Text]]=...) -> None:
        ...

    def HasField(self, field_name: typing_extensions.Literal['advanced_extensions', b'advanced_extensions', 'base_schema', b'base_schema', 'version', b'version']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['advanced_extensions', b'advanced_extensions', 'base_schema', b'base_schema', 'expected_type_urls', b'expected_type_urls', 'extension_uris', b'extension_uris', 'extensions', b'extensions', 'referred_expr', b'referred_expr', 'version', b'version']) -> None:
        ...
global___ExtendedExpression = ExtendedExpression